fix: add @exodus/bytes and html-encoding-sniffer to external modules
Fixes 502 error in production caused by ES Module require() incompatibility:
- @exodus/bytes/encoding-lite.js is ES Module
- html-encoding-sniffer tries to require() it (CommonJS)
- Marking both as external prevents bundler from trying to process them

Error: require() of ES Module not supported in html-encoding-sniffer